### PR TITLE
added support for VKontakte (aka VK.com)

### PR DESCRIPTION
**Pull request by 4ndrey**
Resolving issue https://github.com/SimplicityMobile/Simplicity/issues/3
Please review and merge if needed.

### CODE REVIEW

**Comment by edjiang** [comment]
Hey @4ndrey, this is awesome! Let me try to test this and merge tomorrow along with Instagram, and get a new version out.

**Comment by 4ndrey** [comment]
Great! Let me know if you have questions ;)

**Comment by edjiang** [comment]
Looks great! I'm going to merge, but there is a part of your documentation that's a off (it mentions Instagram) so I'm going to fix that before releasing.

**Comment by edjiang** [comment]
VK is live on Cocoapods under `1.0.2`!

Keep in mind with the new cocoapods, you might have to manually `pod update` to see the new version. 

```Swift
Simplicity.login(VKontakte()) { (accessToken, error) in
  // Handle access token here
}
```

Thanks so much for your help, @4ndrey! Would love to have you hang out on the Stormpath slack as well: https://talkstormpath.shipit.xyz

**Comment by 4ndrey** [comment]
great news, thanks! yes, sorry for typos - initially it was copy-pasted from Instagram login privider, that's why there were some mentions of it.

**Pull request merged**
